### ISSUE TITLE
Preparing training data

### ISSUE THREAD

**Issue by psorianom** [facebookresearch/TaBERT#1]
Hi ! Thank you for your work. I find it very interesting.

I want to train a custom TaBERT using my own tables and contexts but I am not really sure how to proceed. I would like to know more about the training dataset format. Should the dataset be already linearized, as described in the paper? Could you share a sample of the dataset you used to get a glimpse of it?

Thanks for any insight you may have !

**Comment by pcyin** [comment]
Thanks for your interest! I'll prepare a minimal working example ASAP.

**Comment by psorianom** [comment]
Thank you!

**Comment by monk1337** [comment]
+1

**Comment by Sharathmk99** [comment]
+1

**Comment by Vincentchhsu** [comment]
Hi, i need too, thanks.

**Comment by DevHyung** [comment]
Hi, i need too, thanks.

**Comment by pcyin** [comment]
Hey!

Sorry for the delay! I've updated the repo with code for extracting tables from CommonCrawl and Wikipedia, training data generation, and model training.
